### ISSUE TITLE
Finish Auth (pre-Runway)

### ISSUE THREAD

**Issue by KennyTV** [PaperMC/Hangar#100]
Yeah, so things that have to happen here...
- [x] test /api/sync_sso with HangarAuth
- [x] finish organization creation (remove manually insertion of org user into user tables on hangar's end)
- [x] ~~Runway??~~

**Comment by Machine-Maker** [comment]
Yeah, so things that have to happen here...
- [ ] test /api/sync_sso with HangarAuth

**Comment by Machine-Maker** [comment]
I think the solution (as discussed in discord), is to have hangar auth to a manual post to /api/sync_sso in hangarauth's create user endpoint. The database will call it again async, but it shouldn't matter.

**Comment by Machine-Maker** [comment]
Runway will probably not be done initially. So this is done.
