### ISSUE TITLE
v1 api routes

### ISSUE THREAD

**Issue by Machine-Maker** [PaperMC/Hangar#102]
v1 is the internal api used only by the frontend for dynamic content.

- [x] POST    /api/sync_sso
- [x] POST    /api/v1/projects/:pluginId/keys/new
- [x] POST    /api/v1/projects/:pluginId/keys/revoke
- [x] GET     /api/projects/:pluginId/versions/recommended/download
- [x] GET     /api/projects/:pluginId/versions/:name/download
- [ ] GET     /api/v1/projects/:pluginId/versions/recommended/download
- [ ] GET     /api/v1/projects/:pluginId/versions/:name/download
- [x] GET     /api/v1/projects
- [x] GET     /api/v1/projects/:pluginId
- [x] GET     /api/v1/projects/:pluginId/versions
- [x] GET     /api/v1/projects/:pluginId/versions/:name
- [ ] POST    /api/v1/projects/:pluginId/versions/:name
- [x] GET     /api/v1/projects/:pluginId/pages
- [x] GET     /api/v1/users
- [x] GET     /api/v1/users/:user
- [x] GET     /api/v1/projects/:plugin/tags/:versionName
- [x] GET     /api/v1/tags/:tagId
- [x] GET     /api

**Comment by MiniDigger** [comment]
also consider with we actually need those, or if they should be moved to apiv2 instead (and we can then reset the version back to 1 for that)

**Comment by Machine-Maker** [comment]
No longer needed. Use #178 
v1 api is being phased out completely.
