### ISSUE TITLE
v2 api routes

### ISSUE THREAD

**Issue by Machine-Maker** [PaperMC/Hangar#103]
v2 is the external public api

- [x] POST    /authenticate
- [x] POST    /authenticate/user
- [x] DELETE  /sessions/current
- [x] POST    /keys
- [x] DELETE  /keys
- [x] GET     /permissions
- [x] GET     /permissions/hasAll
- [x] GET     /permissions/hasAny
- [x] GET     /projects
- [x] GET     /projects/:pluginId
- [x] GET     /projects/:pluginId/members
- [x] GET     /projects/:pluginId/stats
- [x] GET     /projects/:pluginId/versions
- [x] GET     /projects/:pluginId/versions/:name
- [x] GET     /projects/:pluginId/versions/:version/stats
- [ ] POST    /projects/:pluginId/versions
- [x] GET     /users/:user
- [x] GET     /users/:user/starred
- [x] GET     /users/:user/watching

**Comment by MiniDigger** [comment]
#314
