### ISSUE TITLE
Figure out the discussion page

### ISSUE THREAD

**Issue by KennyTV** [PaperMC/Hangar#115]
Options basically are:
* ~~Store discussion content on our own~~ *Apparently there is people actually liking Discourse and not having any interaction features*
* Use the same kind of Discourse integration to the Paper forums that SpongeOre uses for its own forums

--
* With the first option, we might as well make individual messages look nicer (and not as bare-boned/soulless as Discourse)
* Reactions should be possible, but only with a selected few emojis (but a couple more than GH for example)
* Have a simple reply button, adding a short view of the message that is replied to in the text field

**Comment by MiniDigger** [comment]
this is pretty much done for MVP: we embed discourse
