### ISSUE TITLE
Version Reviews - add link back to version

### ISSUE THREAD

**Issue by Machine-Maker** [PaperMC/Hangar#124]
On the version reviews page, there isn't a link back to the version or project page. There probably should be for ease of use.

**Comment by MiniDigger** [comment]
seems fixed?
![https://i.imgur.com/ewD6FFL.png](https://i.imgur.com/ewD6FFL.png)

**Comment by Machine-Maker** [comment]
Yeah.... I think I added this a while back. Unless I was talking about some other page but I totally forget now :shrug:
