### ISSUE TITLE
BBCode->MD converter for Spigot/DBO users

### ISSUE THREAD

**Issue by KennyTV** [PaperMC/Hangar#136]
Make the jump to Hangar ever so slightly nicer by adding a button/field on project creation to import a ReadMe's contents, or to convert a Spigot resource page's description from BBCode to Markdown.
* A tab for the actual converter with plain text output
* A tab to preview the rendered markdown output
* A tab telling people how to get the BBCode from their Spigot project

**Comment by Machine-Maker** [comment]
This should probably be done before MVP. It's not an overly complex feature to add.

**Comment by MiniDigger** [comment]
Also DBO so that enginehub peeps are happy

**Comment by Machine-Maker** [comment]
Doesn't DBO use bb code? Or at least there is a BB Editor there. I think we can probably just provide a link to a converter right? unless there is something out there we can implement ourselves.

**Comment by MiniDigger** [comment]
bb to markdown could be just lazily implemented with a few regex I guess: https://github.com/JonDum/BBCode-To-Markdown-Converter/blob/gh-pages/index.js#L19

point is, we want to make it as easy as possible to adopt hangar, if there is a simple "import from spigot/dbo" button, that takes your description and maybe even the last releases, that would help adoption
