### ISSUE TITLE
Convert to Vue components

### ISSUE THREAD

**Issue by Machine-Maker** [PaperMC/Hangar#139]
An ongoing list of bits and pieces that should be converted to Vue components.

- [x] project creation
- [x] project settings
- [ ] org creation
- [x] member list (project/organization)
- [x] version creation
- [x] user search bar (for better name suggestion)
- [x] channel creation (probably?)
- [x] api key creation (probably?)
- [x] stats page
- [x] user admin page
- [x] version review log
- [x] version approvals

**Comment by Machine-Maker** [comment]
#177 should tick a few of these off the list.

**Comment by Machine-Maker** [comment]
should the version reviews page be a vue component as well? there's a bunch of buttons as well as a list of review messages. But its not super complex and works fine as it is now.

**Comment by MiniDigger** [comment]
I mean, the more jquery we remove the better I guess

**Comment by MiniDigger** [comment]
#314
