### ISSUE TITLE
dark theme / @media (prefers-color-scheme: dark) {

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/Hangar#140]
prolly wanna finish vue migration first I guess, also compare to https://github.com/PaperMC/papermc.io/issues/50

**Comment by Machine-Maker** [comment]
If we really wanted to be close to papermc.io, we'd switch to materialize as the front end style framework since that has a more materialized feel to it.  But that might be too much work.

**Comment by MiniDigger** [comment]
I mostly was speaking about colors, I don't think its practical to switch away from bootstrap, we use quite a few of its features

**Comment by MiniDigger** [comment]
yeah so bootstrap is rip, #314
