### ISSUE TITLE
Fix and expand dependency sidebar

### ISSUE THREAD

**Issue by KennyTV** [PaperMC/Hangar#142]
With plugin ids being removed (https://github.com/PaperMC/Hangar/pull/141), project dependencies need to be updated as well, also with multi-platform support in mind.
This *could* mean:
* Searching a dependency on Hangar by slug and linking it by default if a match is found
* Being able to manually unlink a dep and set links yourself in project settings (possibly to other websites)
* Having dependencies **per platform** - in settings they have to be separated, and they have to be slightly separated in the project sidebar with the platform name as their header/split

**Comment by Machine-Maker** [comment]
Implemented in #161
