### ISSUE TITLE
html template thru webpack -> file name hashes for assets/js/css

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/Hangar#145]

**Comment by 112RG** [comment]
I am assuming this is about using a hash in the static asset filename? Like `script.7e2c49a622975ebd9b7e.js`

**Comment by Machine-Maker** [comment]
How would this work? Like how would we update the hashes in the templates that load the various static files?

**Comment by MiniDigger** [comment]
Webpack would detect the references to the entry points in the templates and replace them. I bet there is a webpack plugin for that.
Otherwise we can handle hashes on the spring side, spring had a version resource resolver for that. Actually, thinking about it, that's much easier and should be a one liner.

**Comment by 112RG** [comment]
Yep webpack can do it with https://webpack.js.org/guides/caching/ under "Output Filenames". I would think its better todo it in webpack rather then adding more load onto spring?

**Comment by Machine-Maker** [comment]
right, well that just changes the names of the files... you have to update the references in the .ftlh files. Webpack doesn't automatically do that. (at least without the plugin mini mentioned)

**Comment by MiniDigger** [comment]
Issue is how do we get the info of the names into the spring freemarker templates. There is no load for spring, it will cache the hashes for the files. It's just the easier way. I'll implement that today if I get the chance

**Comment by 112RG** [comment]
Oh right my understanding was the frontend did all that. I didn't know the java app worried about the frontend stuff

**Comment by 112RG** [comment]
Does the spring one change the filename too? That is needed for CF caching of the assets

**Comment by MiniDigger** [comment]
Not physically, no. But it adds a filter, that makes sure you can do mycss-hash.css and get served mycss.css

**Comment by 112RG** [comment]
Hmm that could be a problem with CF. Since IIRC the filename requesting needs to change. You can still purge everything from the CF cache but that seems kinda inelegant

**Comment by 112RG** [comment]
Oh actually cloudflare uses etags (forgot about this). Seems that ETag's are on by default on Express. So there should be no need for using any of the webpack/spring VersionResourceResolver unless you don't want to use ETag's that is

**Comment by MiniDigger** [comment]
Oh yeah, def should enable etags, but having hashes is still saver, can just have both

**Comment by 112RG** [comment]
I guess both will work
