### ISSUE TITLE
Suggest(Feat): Github Releases integration. 

### ISSUE THREAD

**Issue by steviebeenz** [PaperMC/Hangar#165]
Allow resources to be auto updated using github releases, and copy version + description from the release.

This would need some limitations (1 file releases only etc)

**Comment by Machine-Maker** [comment]
You mean with gh webhooks?

**Comment by steviebeenz** [comment]
> You mean with gh webhooks?

That could be a way to implement it...

**Comment by KennyTV** [comment]
Duplicate of #39, even if it's just a button on version creation
