### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by steviebeenz** [PaperMC/Hangar#166]
Extend https://github.com/PaperMC/Hangar/issues/136 and https://github.com/PaperMC/Hangar/issues/39 
To add:
- An option to automatically pull description from readme when updated
- Prebuilt github action with Webhook implementation or however else you might implement an automatic deploy to dev channel
- Automatically sync releases, and move over more info than may not be possible in webhooks like description, file, channel (pre or main)
- Github Packages (and maybe jitpack?) links and auto updating widget to display latest version and pom/gradlefile copy paste info to add to repo.
- Issue/PR Count? 
- Last Commit date? 

More?

**Comment by Machine-Maker** [comment]
The project has a link to the source if the project author provides one.

**Comment by electronicboy** [comment]
github action would just release to github, and would be covered over the standard thing of #39, maybe a manual sync option, but, monitoring repos for releases is not a viable option long term
