### ISSUE TITLE
Migrate JQuery to Axios/ES6+Babel

### ISSUE THREAD

**Issue by steviebeenz** [PaperMC/Hangar#186]
Migrate JQuery to Axios/ES6+Babel

Is this planned?

**Comment by Machine-Maker** [comment]
yes, and its underway right now. One big vue component that has a TON of jquery cause I was annoyed with it is the CreateVersion.vue page. Lots of that can be replaced with vue stuff.

And all the files in frontend/src/js will eventually be removed, when they are replaced with vue components.

**Comment by steviebeenz** [comment]
Which should I start on?

**Comment by MiniDigger** [comment]
> And all the files in frontend/src/js will eventually be removed

It still might have sense to extract common staff out of the Vue components into js files, API calls for example

**Comment by Machine-Maker** [comment]
we have api calls in api.js right?

**Comment by MiniDigger** [comment]
yeah, it was just a (bad) example that came to my mind while I wasnt fully awake yet

**Comment by MiniDigger** [comment]
#314
