### ISSUE TITLE
Versions infinitely load for signed-out users on projects with no approved versions

### ISSUE THREAD

**Issue by Chew** [PaperMC/Hangar#211]
Example: https://hangar.minidigger.me/Chew/SpigotDrama/versions

When signed in as a user with no access to manage the project: No versions are listed (intentional)

When signed in as a user who can manage the project: View all versions just fine.

When signed out: Infinitely loads, never works, very sad!

**Comment by Machine-Maker** [comment]
Can you see in the network tab of dev tools what request is failing? It's either the authenticate or the request that returns the versions.

**Comment by Chew** [comment]
Yep! https://hangar.minidigger.me/api/v1/projects/Chew/SpigotDrama/versions?limit=10&offset=0 was the failing URL.
