### ISSUE TITLE
Plugin versions - allow post creation editing.

### ISSUE THREAD

**Issue by Narimm** [PaperMC/Hangar#213]
Allow editing of plugin versions to adjust certain features 

- Dependencies
- Channels 
- Supported Applications 

This will help reduced version deletion due to errors on creation

**Comment by Machine-Maker** [comment]
I can see needing to edit the dependencies on a version, but the channel? I think that's more of a static thing. Or do you have a use case in mind?

**Comment by Narimm** [comment]
I was more concerned regarding errors on version creation - I mean moving a version from development to release would be an example - but in general atleast in my ci I that would be a new version.

**Comment by Machine-Maker** [comment]
Ok, this has been implemented (w/o the channel editing). Can be re-opened if people think its a good idea to be able to change the release channel of a version, but that sounds like a thing that shouldn't change.
