### ISSUE TITLE
Plugin Icon - resets 

### ISSUE THREAD

**Issue by Narimm** [PaperMC/Hangar#214]
The uploader seems to work fine and it appears to save and appears updated in the plugin list but after logging out and in it appears to either have reset or not saved.

Steps to reproduced
1 Edit plugin
2. Upload new icon
![image](https://user-images.githubusercontent.com/2214955/97649457-1ccb2980-1aa3-11eb-932b-91164fa42729.png)
3. Save ✔️ 
4 Check main plugin page updated ✔️ 
![image](https://user-images.githubusercontent.com/2214955/97649512-3cfae880-1aa3-11eb-9cbb-374700b1155e.png)
5.  Now wait - at some point its resetting back to the users avatar.  (It might be after a redeploy?)

**Comment by MiniDigger** [comment]
Am placing my bets on that your settings haven't been saved so you only see the pending icon.
did you get a confirmation after pressing save?

**Comment by Narimm** [comment]
So after you upload it gives you a little message reminding you to Save ...which I do - but there is no confirmation  after you press save but the page updates with the new icon...and when you logout and reload the main page as you can see in the image above it does save

**Comment by Narimm** [comment]
I just re loaded it again ( it had reset and was back to my avatar )

**Comment by Narimm** [comment]
![image](https://user-images.githubusercontent.com/2214955/97697162-59724180-1af2-11eb-8855-3c2a97a17542.png)

**Comment by DarkEyeDragon** [comment]
Can confirm.
The same issue happens to me.
In the comment above you can see the icon set for RandomTeleport but it changed back to the authors avatar at some point (not sure what causes it).
![image](https://user-images.githubusercontent.com/6131099/97707602-cf0cec00-1ab7-11eb-82ec-0d32a1426ea3.png)

**Comment by MiniDigger** [comment]
pls try again

**Comment by DarkEyeDragon** [comment]
After reuploading the icon it seems to work now (it was set to the users pfp for some reason).

**Comment by Machine-Maker** [comment]
Yeah, the default is the owners pfp

**Comment by Narimm** [comment]
I dont believe this is fixed in fact this morning Prism's icon is on the Testproject....
![image](https://user-images.githubusercontent.com/2214955/97820768-6c0b9700-1cfb-11eb-8602-e04409da5352.png)

**Comment by Machine-Maker** [comment]
This was fixed in b86ccf0edf7626ae2f5ffef507e7a8e943e194b4. I believe MiniDigger was just doing some testing and used your icon on TestProject. Nothing to worry about there.
