### ISSUE TITLE
Deleting a Version - the deleted version name is reported as still existing

### ISSUE THREAD

**Issue by Narimm** [PaperMC/Hangar#215]
Replication:
1. Create a version
2. Save
3. Delete the Version
4. Create a new Version with the same name - get the Error that a version with that name already exists.

**Comment by MiniDigger** [comment]
duplicate check needs to ignore (soft)deleted stuff, we need to check what will happen in an admin reverts the deletion

**Comment by Machine-Maker** [comment]
Ok, so solution as talked about is probably removing the unique check on version name allowing a user to upload multiple versions with the same name to one project.

The url format would need to be changed as well to `<version>.<id>` (e.g. `3.0-SNAPSHOT.221`)
