### ISSUE TITLE
Converting BBCode does not convert ICODE tags

### ISSUE THREAD

**Issue by Malfrador** [PaperMC/Hangar#216]
The [ICODE] BBCode tags for inline code do not get converted by the converter.

How it looks on the Spigot page:
![chrome_2020-10-30_12-44-37](https://user-images.githubusercontent.com/6106558/97701526-dcbd7400-1aad-11eb-902b-bd0440273387.png)
How it looks on Hangar:
![chrome_2020-10-30_12-47-07](https://user-images.githubusercontent.com/6106558/97701657-0aa2b880-1aae-11eb-9766-53b5f920c442.png)

**Comment by Machine-Maker** [comment]
That should be replaced with "graves" right? `proxyspawn.exempt`

**Comment by Malfrador** [comment]
Yep.
