### ISSUE TITLE
Upload plugin version button does not match template

### ISSUE THREAD

**Issue by DarkEyeDragon** [PaperMC/Hangar#219]
![image](https://user-images.githubusercontent.com/6131099/97706103-69b7fb80-1ab5-11eb-8500-ec6d79510872.png)
The upload button does not match the overal theme of other pages.

![image](https://user-images.githubusercontent.com/6131099/97706179-894f2400-1ab5-11eb-9271-e015fed7328d.png)

**Comment by Machine-Maker** [comment]
I was thinking that button maybe shouldn't be located there in the first place?

**Comment by DarkEyeDragon** [comment]
Where would you put it then?

**Comment by Machine-Maker** [comment]
I was thinking this perhaps ![new location](https://cdn.discordapp.com/attachments/746367733699969104/771760446188290108/unknown.png)

**Comment by MiniDigger** [comment]
![https://i.imgur.com/gYiQh1Q.png](https://i.imgur.com/gYiQh1Q.png)
