### ISSUE TITLE
Plugin description spoilers

### ISSUE THREAD

**Issue by AlexProgrammerDE** [PaperMC/Hangar#229]
This is a useful feature github implemented as an example:
<details>
  <summary>Spoiler warning</summary>
  
  Spoiler text. Note that it's important to have a space after the summary tag. You should be able to write any markdown you want inside the `<details>` tag... just make sure you close `<details>` afterward.
  
  ```javascript
  console.log("I'm a code block!");
  ```
  
</details>

````markdown
<details>
  <summary>Spoiler warning</summary>
  
  Spoiler text. Note that it's important to have a space after the summary tag. You should be able to write any markdown you want inside the `<details>` tag... just make sure you close `<details>` afterward.
  
  ```javascript
  console.log("I'm a code block!");
  ```
  
</details>
````

Useful links: 
https://github.com/vsch/flexmark-java/wiki/Extensions#admonition

**Comment by AlexProgrammerDE** [comment]
I also found these 3 nice addons. Adding those would be really nice.
https://github.com/vsch/flexmark-java/wiki/Extensions#emoji
https://github.com/vsch/flexmark-java/wiki/Extensions#footnotes
https://github.com/vsch/flexmark-java/wiki/Extensions#gfm-users

**Comment by MiniDigger** [comment]
https://streamable.com/fg6ja9
