### ISSUE TITLE
HangarAuth http redirect

### ISSUE THREAD

**Issue by kadenscott** [PaperMC/Hangar#259]
When creating (and deleting) a project (via https://hangar.minidigger.me/bluely/BlockLoc/manage, for example), I am redirected to an non-HTTPS URL for HangarAuth, resulting in my browser bitching about unsecure connections.

![](https://images-ext-2.discordapp.net/external/OgUtPOW1KTLNCtxAKGXrzLAms86DGkHEMyXXE3e8tNU/https/i.imgur.com/ZtWjfyW.png?width=1202&height=676)

**Comment by MiniDigger** [comment]
can you please describe your url chain? like what url did you call (and where you authed at that time), and what redirects did you encounter along the way

**Comment by kadenscott** [comment]
I don't recall the specific url chain, but I can consistently recreate it, so I'll describe a recreation here.

I am authed/logged in as `bluely`, at https://hangar.minidigger.me/bluely/test1/manage.

Scrolled down, pressed Delete, entered my reason, pressed Delete on the modal, and am redirected to http://hangar.minidigger.me/ with the "Form is not secure" message. Interestingly, it seems like the form is sent anyways, as going back without pressing "Send anyways" shows me that my project has been deleted.
