### ISSUE TITLE
Header anchor icons and text are disproportionately huge in Markdown previews

### ISSUE THREAD

**Issue by mdcfe** [PaperMC/Hangar#266]
When previewing a changelog on the "release a new version" page:

![firefox_2020-12-14_21-29-01](https://user-images.githubusercontent.com/1917406/102137870-6903da80-3e53-11eb-960e-be86e85514ab.png)

Both the headings and the anchor link icon seem way too big in context, especially as those are supposed to be h2 and h3 tags. There could also be a bit more spacing above headings?

An idea mocked up:
- h2 text reduced to 1.5rem
- h3 text reduced to 1.3rem
- icon resized from 1em to 0.7em, made grey except for on hover and 0.3em right padding

![firefox_2020-12-14_21-38-36](https://user-images.githubusercontent.com/1917406/102138790-d106f080-3e54-11eb-8c3a-c8a9bba79cfd.png)

vs original:

![2020-12-14_21-40-23](https://user-images.githubusercontent.com/1917406/102138898-feec3500-3e54-11eb-90a4-91bbcc57aabd.png)

**Comment by Machine-Maker** [comment]
Yeah, so at some point, **all** the styling for the markdown stopped working. I found the issue.
