### ISSUE TITLE
Can download latest version... even if there are "none"

### ISSUE THREAD

**Issue by Chew** [PaperMC/Hangar#276]
Example: https://hangar.minidigger.me/mdcfe/EssentialsX

You can click download, and it works fine, but nothing shows up in the Versions tab.

**Comment by Machine-Maker** [comment]
A solution might be to prevent setting a version as recommended if it doesn't have Public visibility

**Comment by Chew** [comment]
I can't see anything on the version list, verified or not. Signing in doesn't change this, there's just nothing there

**Comment by Machine-Maker** [comment]
No I know, but there is a version. I can see it on my Admin account. I don't think you have the SeeHidden permission.
