### ISSUE TITLE
Setting PFP to a gif

### ISSUE THREAD

**Issue by PeachesMLG** [PaperMC/Hangar#290]
When setting your profile picture to a gif loads of stuff breaks.

https://imgur.com/mBRUKQp.png

And the pfp endpoint gives errors: https://imgur.com/9BG40pV.png

**Comment by MiniDigger** [comment]
I was faster :P
https://github.com/PaperMC/HangarAuth/issues/6

**Comment by PeachesMLG** [comment]
:C
