### ISSUE TITLE
Cant validate Dependancy

### ISSUE THREAD

**Issue by PeachesMLG** [PaperMC/Hangar#293]
Not sure if this is actually an error or im just an idiot.

So I accidentally put Vault as both a soft and hard dependency in my plugin.yml meaning that I had to provide a link to download Vault twice. However when I put the link in the soft dependency one it kept giving me an error: https://i.imgur.com/vuBjYa8.png The hard dependency one worked fine.

Not sure if this is a weird bug or if im being stupid. Either way this helped me realize I had Vault as both a hard and soft dependency lol

https://i.imgur.com/vuBjYa8.png

**Comment by Machine-Maker** [comment]
Reproduce on https://hangar-new.minidigger.me
Most of this stuff has been redone.
