### ISSUE TITLE
Resource edit buttons are not hidden if user lacks permissions

### ISSUE THREAD

**Issue by Prof-Bloodstone** [PaperMC/Hangar#484]
If you go to resource version page in private browser: https://hangar.benndorf.dev/MiniDigger/Test/versions/5.2.35/paper
You'll notice, that you have orange edit buttons available, which open the appropriate edit menu:
![image](https://user-images.githubusercontent.com/46570876/120938914-8b492780-c715-11eb-9f60-b5a002608853.png)
They should be hidden, if user doesn't have permission to edit resource.

You can't submit the change, as backed returns "You must be logged in" error.

**Comment by MiniDigger** [comment]
Should be an easy PR
https://github.com/PaperMC/Hangar/blob/master/frontend/components/modals/versions/DependencyEditModal.vue#L4
Needs an v-if $perms.canEditProject or however the perm is called, else hopefully I can take a look tomorrow

**Comment by Machine-Maker** [comment]
Wow, is this like, the first legit bug issue?

**Comment by MiniDigger** [comment]
The first of many ^^

**Comment by Machine-Maker** [comment]
Oh yeah, can't wait for that.

**Comment by Chew** [comment]
I've reported a few >:(

**Comment by electronicboy** [comment]
> I've reported a few >:(

https://www.youtube.com/watch?v=5sBhc8je8Y0
