### ISSUE TITLE
Proper multi-platform support

### ISSUE THREAD

**Issue by KennyTV** [PaperMC/Hangar#96]
* [x] Auto detect Paper/Waterfall/Velocity/... platforms as good as it gets and check those on project creation (as already done), but let the user check those manually as well (for example with the ambiguous plugin.yml / plugins working on multiple platforms w ambiguity) - one project has to be viewable/findable in multiple platform categories.
* [x] Make sure the project (not only version) page clearly shows what platforms the project works on.
* [ ] The initial plan was for discussion to be sent to the Paper forum's plugin category, embedded in Hangar - this won't work for any other generic platform / would be limiting - what to do? (。_。)
* [x] Dependencies should be listed under their platform (= have slightly separated sublists for dependencies).

**Comment by Machine-Maker** [comment]
Ok, so is it best for each version uploaded to only have 1 platform, and use release channels for different platforms, or should each version uploaded allow multiple platforms to be selected?

I think its best that each version uploaded (essentially each row in the db) should only be 1 platform. I think that simplifies things pretty dramatically. If we go that route, we can add a platform column to the versions table. Then the dependencies column in the versions table could solely be for other plugin dependencies. probably changing that column type to JSONB and using a format similar to this
```json
[
  {
    "name": "name as it is in plugin.yml",
    "required": true,
    "project_id": 3, 
    "link": "url",
    "versions": [
      { "release_channel_id": 3, "version_string": "1.3" },
      { "release_channel_id": 3, "version_string": "1.4" }
    ]
  },
  ...
]
```

I would like some feedback on this.

**Comment by A248** [comment]
> Ok, so is it best for each version uploaded to only have 1 platform, and use release channels for different platforms, or should each version uploaded allow multiple platforms to be selected?

The way I do things, I prefer to distribute a single jar with support for multiple platforms. It makes user transitions and providing support and updates easier. Some other plugins I know of also follow this pattern.

**Comment by Machine-Maker** [comment]
@A248 do you know if its standard for plugins that do this to also have the same version name/number for each platform?

**Comment by A248** [comment]
All the plugins I know of which do this use the same version number for each platform.

**Comment by Machine-Maker** [comment]
K, so if that is the case, I think having the ability to release a version on multiple channels, so you are still only uploading the file once, but it goes to all the channels for all the platforms selected.

**Comment by Machine-Maker** [comment]
Partially implemented in #161 


On the first checkbox item...
Hangar detects the platforms with 100% accuracy. It literally iterates through all the files inside of a jar until it finds either plugin.yml, bungee.yml, or velocity-config.json and the loads metadata from there. So the way it’s currently setup, if the user provides a file, they **cannot** change what platforms are selected.

**Comment by Machine-Maker** [comment]
On the 3rd point, I think the consensus was that each plugin will get one thread on discourse regardless of which platforms it supports. If I got that right, then this can probably be closed.

**Comment by KennyTV** [comment]
Yup!
