### ISSUE TITLE
Add supported version selector

### ISSUE THREAD

**Issue by KennyTV** [PaperMC/Hangar#97]
Since the full range of supported versions can't be detected automatically and so that people don't have to put it into their docs manually, add checkboxes for version support in project settings and have a small display on the project's sidebar

**Comment by Machine-Maker** [comment]
I wonder if we should use the existing paper api to get a list of versions for paper/waterfall. Does velocity have the same thing?

**Comment by KennyTV** [comment]
There's no way to get that from API. It's impossible to analyze what versions are supported without the user manually setting it *somewhere*

**Comment by MiniDigger** [comment]
I would argue minecraft version is enough?

**Comment by KennyTV** [comment]
How does the user know something's abandoned vs. just didn't need any updates to support a new version then? You can't really slap a single version onto most plugins (and especially not on upload, since you don't always have update your plugin on every release) :p

**Comment by md678685** [comment]
Paper and Waterfall's versioning schemes effectively match MC versions, but Velocity has both 1.0.x and 1.1.0 APIs. I'd second having a checkbox list of supported platform versions similar to BukkitDev/CurseForge does it.

**Comment by Chew** [comment]
https://papermc.io/api/v1/paper

**Comment by Machine-Maker** [comment]
Should the supported version selector completely replace the current system? currently, hangar looks at the plugin.yml for the api-version. which sometimes won't be there, and sometimes is wrong, or whatever. 

So I think that should be removed, and completely replaced with a manual version selector.

**Comment by md678685** [comment]
We could use the detection to pre-fill the list on upload, so if it's correct the user won't have to do anything.

**Comment by Machine-Maker** [comment]
sure yeah. so if the api version exists, itll pre-fill that checkbox
