### ISSUE TITLE
Support linking external download site per version

### ISSUE THREAD

**Issue by Machine-Maker** [PaperMC/Hangar#99]
Support external download link when creating a new version instead of uploading a jar/zip file.

Mainly for projects that would require multiple jar uploads with the same version strings (plugins that support multiple platforms).

**Comment by KennyTV** [comment]
+ Have a whitelist for allowed sites to link to with a warning displayed otherwise

**Comment by Chew** [comment]
Warning would be something like "This site has not been verified by the PaperMC Team. The site may be unsafe or unavailable, and we are not responsible for site outages or other problems. Click to continue to the site away." as a middleman page I suppose.
